// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfOXdbdQdqpNl60iyWYMX2udqw7fAP2bc',
    appId: '1:350882100092:web:29c46c576e9425d283eaf9',
    messagingSenderId: '350882100092',
    projectId: 'construction-industry-b8020',
    authDomain: 'construction-industry-b8020.firebaseapp.com',
    storageBucket: 'construction-industry-b8020.appspot.com',
    measurementId: 'G-KN8Z34H04V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiHb7cSOtYZr3gqZlALaT2DXyTyxlqqkI',
    appId: '1:350882100092:android:00a3ce0075f15d6983eaf9',
    messagingSenderId: '350882100092',
    projectId: 'construction-industry-b8020',
    storageBucket: 'construction-industry-b8020.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCChA7fnD8jFtgjZmH-802t5y9lDiZZJcE',
    appId: '1:350882100092:ios:5c3da02e43eebb0c83eaf9',
    messagingSenderId: '350882100092',
    projectId: 'construction-industry-b8020',
    storageBucket: 'construction-industry-b8020.appspot.com',
    iosClientId: '350882100092-mbt6c6m5jq8ihql0oggkpdslbspi1c9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.procurementForConstructionIndustry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCChA7fnD8jFtgjZmH-802t5y9lDiZZJcE',
    appId: '1:350882100092:ios:5c3da02e43eebb0c83eaf9',
    messagingSenderId: '350882100092',
    projectId: 'construction-industry-b8020',
    storageBucket: 'construction-industry-b8020.appspot.com',
    iosClientId: '350882100092-mbt6c6m5jq8ihql0oggkpdslbspi1c9k.apps.googleusercontent.com',
    iosBundleId: 'com.example.procurementForConstructionIndustry',
  );
}
